apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deploy
  labels:
    app: my-web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-deploy
  template:
    metadata:
      labels:
        app: my-web-deploy
    spec:
      containers:
        - image: my-web-app:1.0
          name: my-web-app-container
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
