apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    type: web-app
  name: my-web-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      type: web-app
  template:
    metadata:
      labels:
        type: web-app
    spec:
      containers:
        - image: my-web-app:1.0
          name: my-web-app-container
      restartPolicy: Always
