apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-web-rs
  labels:
    app: my-web-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-rs
  template:
    metadata:
      labels:
        app: my-web-rs
    spec:
      containers:
        - image: my-web-app:1.0
          name: my-web-app-container
      restartPolicy: Always
